<template>
  <ProductDetail
    name="Mod V"
    slug="mod-v"
    tagline="For the largest yachts and extreme torque requirements"
    description="ShaftLok Mod V - Ultimate marine propeller control system with performance-grade locking technology. Maximum propeller control for high-value vessels and critical marine operations."
    og-title="Shaft Lok Mod V - Ultimate Marine Propeller Control System"
    image="/assets/images/shaftlok-mod-purple.jpg"
    image-alt="Shaft Lok Mod V marine propeller control system - ultimate design for largest yachts and extreme torque requirements with performance-grade locking technology"
    bore="150mm"
    category="Custom Mega-Yacht Series"
    :features="features"
    :specs="specs"
  >
    <p>The Maximum Propeller Shaft Diameter is to be determined by the application.</p>
    <p>The Shaft Lok Inc. Mod IV, V, and VI units are designed for these yachts.</p>
    <p>These huge yachts are mostly motor vessels but there are a few sailboats like the beautiful restored schooner S/Y ERNESTINA that returned to New Bedford, MA recently. M/Y Rocket One is a million dollar motor yacht, both of these boats are online.</p>
    <p>The captains and owners of these vessels like to just use one engine at times:</p>
    <ol>
      <li>To dramatically increase the miles per gallon of the expensive diesel… which increases the yacht's range.</li>
      <li>Increasing the efficiency of the vessel also reduces the operation monthly hours on the motors stabilizing the yacht's relative value.</li>
      <li>Also, it allows the vessel to keep powering while the other drive train system is being maintained. However, the drive train that is shut down needs it's propeller locked as the vessel is powering on the other motor. Allowing the propeller to freewheel could cause significant transmission damage because the transmission gets it's lubrication from the engine.</li>
    </ol>
    <p>The Shaft Lok unit(s) must be designed to handle massive amounts of torque generated by the yacht speed and propeller size.</p>
    <p>This enormous static torque can be achieved by building a strong single unit using multiple standard short pins, the locking pin and spring systems in the housing to hold the large locking pin stationary.</p>
    <p>This design of the Mod IV, V and VI is just a simple upgrade from the 1979 patented arrangement. The components are designed to handle the loads involved.</p>
    <p>Please submit your yacht details including the yacht's name and contact information for price and delivery details.</p>
  </ProductDetail>
</template>

<script setup>
const features = [
  { icon: 'fas fa-ruler', title: 'Max Bore Size', text: '150mm' },
  { icon: 'fas fa-lock', title: 'Advanced Locking', text: 'Advanced locking technology' },
  { icon: 'fas fa-shield-alt', title: 'Maximum Security', text: 'Maximum security and performance' },
  { icon: 'fas fa-industry', title: 'Heavy-Duty', text: 'Designed for heavy-duty applications' }
]

const specs = [
  { name: 'Max Bore Size', value: '150mm' },
  { name: 'Suitable For', value: 'Largest yachts and extreme torque requirements' },
  { name: 'Design', value: 'Multiple standard short pins, locking pin and spring systems' },
  { name: 'Ordering', value: 'Submit yacht details for price and delivery' }
]

definePageMeta({
  layout: 'default'
})
</script>
