<template>
  <ProductDetail
    name="Mod VI"
    slug="mod-vi"
    tagline="Next-generation locking for advanced marine systems"
    description="Shaft Lok Mod VI - Custom marine propeller control system for specialized applications. Tailored solutions for unique vessel requirements and extreme environments."
    og-title="Shaft Lok Mod VI - Custom Marine Propeller Control System"
    image="/assets/images/shaftlok-mod-purple.jpg"
    image-alt="Shaft Lok Mod VI marine propeller control system - custom design for specialized applications and unique vessel requirements with extreme environment capabilities"
    bore='6.5" (165.1mm)'
    category="Custom Mega-Yacht Series"
    :features="features"
    :specs="specs"
  >
    <p>The Maximum Propeller Shaft Diameter is 6.5" (165.1mm).</p>
    <p>The Shaft Lok Inc. Mod IV, V and VI units are designed for these yachts.</p>
    <p>These huge yachts are mostly motor vessels but there are a few sailboats like the beautiful restored schooner S/Y ERNESTINA that returned to New Bedford, MA recently. M/Y Rocket One is a million dollar motor yacht, both of these boats are online.</p>
    <p>The captains and owners of these vessels like to just use one engine at times:</p>
    <ol>
      <li>To dramatically increase the miles per gallon of the expensive diesel. This will increase the yacht's range.</li>
      <li>Increasing the efficiency of the vessel also reduces the operation monthly hours on the motors stabilizing the yacht's relative value.</li>
      <li>Also, it allows the vessel to keep powering while the other drive train system is being maintained.</li>
    </ol>
    <p>However, the drive train that is shut down needs it's propeller locked as the vessel is powering on the other motor. Allowing the propeller to freewheel could cause significant transmission damage because the transmission gets it's lubrication from the engine.</p>
    <p>The Shaft Lok unit(s) must be designed to handle massive amounts of torque generated by the yacht speed and propeller size.</p>
    <p>This enormous static torque can be achieved by building a strong single unit using multiple standard short pins, the locking pin and spring systems in the housing to hold the large locking pin stationary.</p>
    <p>This design of the Mod IV, V and VI is just a simple upgrade from the 1979 patented arrangement. The components are designed to handle the loads involved.</p>
    <p>Please submit your yacht details including the yacht's name and contact information for price and delivery details.</p>
  </ProductDetail>
</template>

<script setup>
const features = [
  { icon: 'fas fa-ruler', title: 'Max Bore Size', text: '6.5" (165.1mm)' },
  { icon: 'fas fa-microchip', title: 'State-of-the-Art', text: 'State-of-the-art locking technology' },
  { icon: 'fas fa-medal', title: 'Premium Materials', text: 'Premium materials construction' },
  { icon: 'fas fa-star', title: 'Exceptional Performance', text: 'Exceptional performance and security' }
]

const specs = [
  { name: 'Max Bore Size', value: '6.5" (165.1mm)' },
  { name: 'Suitable For', value: 'Specialized applications and unique vessel requirements' },
  { name: 'Design', value: 'Multiple standard short pins, locking pin and spring systems' },
  { name: 'Ordering', value: 'Submit yacht details for price and delivery' }
]

definePageMeta({
  layout: 'default'
})
</script>
