<template>
  <div>
    <BreadcrumbNav :items="[{ name: 'Products', to: '/products' }, { name: 'Mod IV' }]" />
    
    <div class="product-container">
      <div class="product-detail">
        <div class="product-card">
          <h1 class="page-title">Mod IV</h1>
          <h2 class="page-description">For specialty and custom marine applications</h2>
          <div class="product-content">
            <div class="product-image-container">
              <img src="/assets/images/shaftlok-mod-purple.jpg" alt="Shaft Lok Mod IV marine propeller control system - professional-grade design for specialty applications and large motor vessels with custom installation support" class="product-image" loading="lazy">
            </div>
            <div class="product-description">
              <div class="features-grid">
                <div class="feature-item">
                  <h3 class="feature-title">
                    <i class="fas fa-ruler feature-icon"></i>
                    Max Bore Size
                  </h3>
                  <p class="feature-description">4.33" (110mm)</p>
                </div>
                <div class="feature-item">
                  <h3 class="feature-title">
                    <i class="fas fa-ship feature-icon"></i>
                    Large Vessels
                  </h3>
                  <p class="feature-description">Designed for large motor vessels</p>
                </div>
                <div class="feature-item">
                  <h3 class="feature-title">
                    <i class="fas fa-cogs feature-icon"></i>
                    Enhanced Torque
                  </h3>
                  <p class="feature-description">Enhanced torque handling</p>
                </div>
                <div class="feature-item">
                  <h3 class="feature-title">
                    <i class="fas fa-tools feature-icon"></i>
                    Custom Support
                  </h3>
                  <p class="feature-description">Custom installation support</p>
                </div>
              </div>
              <div class="details-text">
                <p>The Maximum Propeller Shaft Diameter is 4.330" (110mm).</p>
                <p>The Shaft Lok Inc. Mod IV, V, and VI units are designed for these yachts.</p>
                <p>These huge yachts are mostly motor vessels but there are a few sail boats like the beautifully restored schooner S/Y ERNESTINA that returned to New Bedford, MA recently. M/Y Rocket One is a million dollar motor yacht, both of these boats are online. The captains and owners of these vessels like to use one engine when:</p>
                <ol>
                  <li>To dramatically increase the miles per gallon of the expensive diesel… which increases the yacht's range.</li>
                  <li>Increasing the efficiency of the vessel also reduces the operation monthly hours on the motors stabilizing the yacht's relative value.</li>
                  <li>Also, it allows the vessel to keep powering while the other drive train system is being maintained. However, the drive train that is shut down needs it's propeller locked as the vessel is powering on the other motor. Allowing the propeller to freewheel could cause significant transmission damage because the transmission gets it's lubrication from the engine.</li>
                </ol>
                <p>The Shaft Lok unit(s) must be designed to handle massive amounts of torque generated by the yacht speed and propeller size.</p>
                <p>This enormous static torque can be achieved by building a strong single unit using multiple standard short pins, the locking pin and spring systems in the housing to hold the large locking pin stationary.</p>
                <p>This design of the Mod IV, V and VI is just a simple upgrade from the 1979 patented arrangement. The components are designed to handle the loads involved</p>
                <p>Please submit your yacht details including the yacht's name and contact information for price and delivery details.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
useHead({
  title: 'Mod IV',
  meta: [
    { name: 'description', content: 'ShaftLok Mod IV - Professional-grade marine propeller control system with advanced locking features. Designed for critical applications requiring maximum propeller control.' },
    { property: 'og:title', content: 'Shaft Lok Mod IV - Professional-Grade Marine Propeller Control' },
    { property: 'og:description', content: 'Shaft Lok Mod IV - Professional-grade marine propeller control system with advanced locking features. Designed for critical applications requiring maximum propeller control.' },
    { property: 'og:image', content: 'https://shaftlok.com/assets/images/shaftlok-mod-purple.jpg' },
    { property: 'og:url', content: 'https://shaftlok.com/products/mod-iv' },
    { property: 'og:type', content: 'website' },
    { property: 'og:site_name', content: 'Shaft Lok Inc.' },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: 'Shaft Lok Mod IV - Professional-Grade Marine Propeller Control' },
    { name: 'twitter:description', content: 'Shaft Lok Mod IV - Professional-grade marine propeller control system with advanced locking features. Designed for critical applications requiring maximum propeller control.' },
    { name: 'twitter:image', content: 'https://shaftlok.com/assets/images/Logo_ShaftLok_whiteBG-landscape.png' }
  ],
  link: [
    { rel: 'canonical', href: 'https://shaftlok.com/products/mod-iv' }
  ],
  script: [
    {
      type: 'application/ld+json',
      children: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: 'https://shaftlok.com/'
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Products',
            item: 'https://shaftlok.com/products'
          },
          {
            '@type': 'ListItem',
            position: 3,
            name: 'Mod IV',
            item: 'https://shaftlok.com/products/mod-iv'
          }
        ]
      })
    },
    {
      type: 'application/ld+json',
      children: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'Product',
        name: 'Mod IV',
        description: 'Professional-grade marine propeller control system for specialty and custom applications. Designed for large motor vessels with enhanced torque handling and custom installation support.',
        brand: {
          '@type': 'Brand',
          name: 'Shaft Lok'
        },
        manufacturer: {
          '@type': 'Organization',
          name: 'Shaft Lok Inc.',
          url: 'https://shaftlok.com'
        },
        image: 'https://shaftlok.com/assets/images/shaftlok-mod-purple.jpg',
        url: 'https://shaftlok.com/products/mod-iv',
        category: 'Marine Equipment',
        additionalProperty: [
          {
            '@type': 'PropertyValue',
            name: 'Max Bore Size',
            value: '4.33" (110mm)'
          },
          {
            '@type': 'PropertyValue',
            name: 'Suitable For',
            value: 'Large motor vessels and specialty applications'
          },
          {
            '@type': 'PropertyValue',
            name: 'Torque Handling',
            value: 'Enhanced torque for demanding applications'
          },
          {
            '@type': 'PropertyValue',
            name: 'Installation',
            value: 'Custom installation support available'
          },
          {
            '@type': 'PropertyValue',
            name: 'Application Type',
            value: 'Million dollar yachts and large vessels'
          }
        ]
      })
    }
  ]
})

definePageMeta({
  layout: 'default'
})
</script>

<style scoped>
.product-container {
  margin-top: 8rem;
  min-height: 100vh;
  background: linear-gradient(to bottom, var(--light-cyan), white);
  padding: 2rem;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.product-detail {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
}

.product-card {
  background-color: white;
  border: 2px solid var(--federal-blue);
  border-radius: 15px;
  padding: 2rem;
  display: flex;
  flex-direction: column;
  gap: 0rem;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  animation: fadeIn 1s ease-out forwards;
  opacity: 0;
  position: relative;
}

.page-title {
  text-align: center;
  color: var(--federal-blue);
  font-family: 'DeVinneOrnamentDRegular', serif;
  font-size: var(--font-size-title);
  margin-top: 1rem;
  margin-bottom: 0;
  animation: fadeIn 1s ease-out forwards;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
  position: relative;
  z-index: 2;
}

.page-description {
  font-size: var(--font-size-subtitle);
  color: var(--federal-blue);
  max-width: 1200px;
  margin: 0 auto;
  margin-bottom: 2rem;
  animation: fadeIn 1s ease-out 0.5s forwards;
  opacity: 0;
  text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.5);
  position: relative;
  z-index: 2;
  text-align: center;
}

.product-content {
  display: flex;
  gap: 2rem;
  padding-top: 2rem;
}

.product-image-container {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 600px;
}

.product-image {
  width: 100%;
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.product-description {
  flex: 2;
  color: #333;
  line-height: 1.6;
  font-size: var(--font-size-description);
  animation: fadeIn 1s ease-out 0.5s forwards;
  opacity: 0;
  height: 600px;
  display: flex;
  flex-direction: column;
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.feature-item {
  text-align: left;
}

.feature-title {
  font-weight: bold;
  color: #333;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: var(--font-size-subtitle);
}

.feature-icon {
  color: var(--honolulu-blue);
  font-size: var(--font-size-icon);
}

.feature-description {
  color: #666;
  font-size: var(--font-size-description);
  margin-top: 0;
  margin-bottom: 0;
  margin-left: 2rem;
}

.details-text {
  flex: 1;
  overflow-y: auto;
  padding-right: 1rem;
  margin-top: 1rem;
  color: #333;
  line-height: 1.6;
}

.details-text::-webkit-scrollbar {
  width: 8px;
}

.details-text::-webkit-scrollbar-track {
  background: rgba(0, 0, 0, 0.1);
  border-radius: 4px;
}

.details-text::-webkit-scrollbar-thumb {
  background: var(--honolulu-blue);
  border-radius: 4px;
}

.details-text::-webkit-scrollbar-thumb:hover {
  background: var(--federal-blue);
}

.details-text p {
  margin-bottom: 1rem;
}

.details-text ol {
  list-style: none;
  padding-left: 0;
  counter-reset: item;
  margin-top: 1rem;
}

.details-text ol li {
  counter-increment: item;
  margin-bottom: 1.5rem;
  padding-left: 2.5rem;
  position: relative;
  line-height: 1.6;
}

.details-text ol li::before {
  content: counter(item);
  position: absolute;
  left: 0;
  top: 0;
  background: var(--honolulu-blue);
  color: white;
  font-weight: bold;
  font-size: 0.9rem;
  width: 1.8rem;
  height: 1.8rem;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 768px) {
  .product-detail {
    padding: 0.5rem;
  }

  .product-card {
    padding: 1.5rem;
    gap: 1.5rem;
  }

  .product-content {
    flex-direction: column;
    gap: 1.5rem;
  }

  .product-image-container {
    width: 100%;
    height: auto;
  }

  .product-description {
    width: 100%;
    height: auto;
  }

  .features-grid {
    grid-template-columns: 1fr;
    gap: 1rem;
  }

  .feature-description {
    margin-left: 0;
    padding-left: 0;
  }

  .feature-icon {
    display: none;
  }
}
</style>