<template>
  <ProductDetail
    name="Mod IV"
    slug="mod-iv"
    tagline="For specialty and custom marine applications"
    description="ShaftLok Mod IV - Professional-grade marine propeller control system with advanced locking features. Designed for critical applications requiring maximum propeller control."
    og-title="Shaft Lok Mod IV - Professional-Grade Marine Propeller Control"
    image="/assets/images/shaftlok-mod-purple.jpg"
    image-alt="Shaft Lok Mod IV marine propeller control system - professional-grade design for specialty applications and large motor vessels with custom installation support"
    bore='4.33" (110mm)'
    category="Custom Mega-Yacht Series"
    :features="features"
    :specs="specs"
  >
    <p>The Maximum Propeller Shaft Diameter is 4.330" (110mm).</p>
    <p>The Shaft Lok Inc. Mod IV, V, and VI units are designed for these yachts.</p>
    <p>These huge yachts are mostly motor vessels but there are a few sail boats like the beautifully restored schooner S/Y ERNESTINA that returned to New Bedford, MA recently. M/Y Rocket One is a million dollar motor yacht, both of these boats are online. The captains and owners of these vessels like to use one engine when:</p>
    <ol>
      <li>To dramatically increase the miles per gallon of the expensive diesel… which increases the yacht's range.</li>
      <li>Increasing the efficiency of the vessel also reduces the operation monthly hours on the motors stabilizing the yacht's relative value.</li>
      <li>Also, it allows the vessel to keep powering while the other drive train system is being maintained. However, the drive train that is shut down needs it's propeller locked as the vessel is powering on the other motor. Allowing the propeller to freewheel could cause significant transmission damage because the transmission gets it's lubrication from the engine.</li>
    </ol>
    <p>The Shaft Lok unit(s) must be designed to handle massive amounts of torque generated by the yacht speed and propeller size.</p>
    <p>This enormous static torque can be achieved by building a strong single unit using multiple standard short pins, the locking pin and spring systems in the housing to hold the large locking pin stationary.</p>
    <p>This design of the Mod IV, V and VI is just a simple upgrade from the 1979 patented arrangement. The components are designed to handle the loads involved</p>
    <p>Please submit your yacht details including the yacht's name and contact information for price and delivery details.</p>
  </ProductDetail>
</template>

<script setup>
const features = [
  { icon: 'fas fa-ruler', title: 'Max Bore Size', text: '4.33" (110mm)' },
  { icon: 'fas fa-ship', title: 'Large Vessels', text: 'Designed for large motor vessels' },
  { icon: 'fas fa-cogs', title: 'Enhanced Torque', text: 'Enhanced torque handling' },
  { icon: 'fas fa-tools', title: 'Custom Support', text: 'Custom installation support' }
]

const specs = [
  { name: 'Max Bore Size', value: '4.33" (110mm)' },
  { name: 'Suitable For', value: 'Specialty and custom marine applications, large motor vessels' },
  { name: 'Design', value: 'Multiple standard short pins, locking pin and spring systems' },
  { name: 'Ordering', value: 'Submit yacht details for price and delivery' }
]

definePageMeta({
  layout: 'default'
})
</script>
